exclude: .*migrations\/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Prevent secrets from being committed
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.25.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]

  # Format code to PEP standards
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.10.11

  # Sort imports alphabetically and automatically separate into sections and by type
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

  # An extremely fast Python linter and code formatter to replace flake8
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # static type checker for Python.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.1'
    hooks:
      - id: mypy
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        additional_dependencies: [
            # mypy dependencies
            djangorestframework,
            djangorestframework-stubs,
            django-stubs,
            python-dotenv,
            psycopg2,
            django-filter,
            djangorestframework-api-key,
            drf-spectacular,
            celery,
            django-db-connection-pool,
            dj-database-url,
            whitenoise,
            sentry-sdk,
        ]
