# Generated by Django 5.0.6 on 2024-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_documents_notes_historicaldocuments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaldocuments",
            name="file",
            field=models.CharField(max_length=100),
        ),
    ]
