# Generated by Django 5.0.6 on 2024-05-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_alter_historicaldocuments_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaldocuments",
            name="file",
            field=models.TextField(max_length=100),
        ),
    ]
