# Generated by Django 5.0.6 on 2024-05-15 14:51

import documents.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_alter_documenttype_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=documents.storage_backends.DocumentStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocuments",
            name="file",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
