# Generated by Django 5.0.6 on 2024-05-15 15:04

import documents.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_alter_documents_file_alter_historicaldocuments_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="file",
            field=models.FileField(
                default="",
                storage=documents.storage_backends.DocumentStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="description",
            field=models.CharField(
                help_text="A brief description of the type of the document",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicaldocuments",
            name="file",
            field=models.TextField(default="", max_length=100),
        ),
    ]
