# Generated by Django 5.0.6 on 2024-05-13 20:04

import commons.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                    ("SENIOR_DOCTOR", "Senior Doctor"),
                ],
                default=commons.constants.UserRoles["PATIENT"],
                max_length=20,
            ),
        ),
    ]
